// needs new entries to be added manually each time a new chapter/tournament releases

export const LOGO_URLS: Record<string, string> = {
    'Season_X': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/Season_X_logo.png',
    'C2S1': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S1_logo.png',
    'C2S2': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S2_logo.webp',
    'C2S2_Invitationals': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S2_Invitationals_logo.webp',
    'C2S3': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S3_logo.webp',
    'C2S4': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S4_logo.webp',
    'C2S5': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S5_logo.webp',
    'C2S6': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S6_logo.webp',
    'All_Star_Showdown': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/All_Star_Showdown_Logo.png',
    'C2S7': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S7_logo.webp',
    'C2S8': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C2S8_logo.webp',
    'Grand_Royale': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/Grand_Royale_logo.webp',
    'C3S1': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C3S1_logo.png',
    'C3S2': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C3S2_logo.png',
    'C3S3': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C3S3_logo.png',
    'Globals_2022': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/Globals_2022_logo.png',
    'C4M1': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C4M1_logo.png',
    'C4M2': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C4M2_logo.png',
    'C4M3': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C4M3_logo.png',
    'Globals_2023': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/Globals_2023_logo.png',
    'C5M1': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C5M1_logo.png',
    'C5M2': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C5M2_logo.png',
    'C5M3': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C5M3_logo.png',
    'Globals_2024': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/Globals_2024_logo.png',
    'C6M1': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C6M1_logo.png',
    'C6M2': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C6M2_logo.png',
    'C6M3': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C6M3_logo.png',
    'Globals_2025': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/Globals_2025_logo.png',
    'C7M1': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C7M1_logo.png',
    'Globals_C7M1_Summit': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/Globals_C7M1_Summit_Logo.png',
    'C7M2': 'https://qukspgqvudaxzsqvmknz.supabase.co/storage/v1/object/public/tournament-logos/C7M2_logo.png',
};